CREATE TABLE MOVIE(
ID NUMBER,
CONSTRAINT MOVIE_PK PRIMARY KEY(ID),
TITLE NVARCHAR2(50) NOT NULL UNIQUE,
DIRECTOR NVARCHAR2(20) NOT NULL,
YEAR NUMBER(4) CHECK(YEAR BETWEEN 1900 AND 2019),
LENGTH_MINS NUMBER(3) CHECK(LENGTH_MINS BETWEEN 10 AND 200)
)

