CREATE TABLE FORUM_POSTS(
    ID NUMBER,
    CONSTRAINT FORUM_POSTS_PK PRIMARY KEY(ID),
    
    ID_FORUM_SUBCATEGORIES NUMBER,
    CONSTRAINT FORUM_SUBCATEGORIES_FK FOREIGN KEY(ID_FORUM_SUBCATEGORIES) REFERENCES FORUM_SUBCATEGORIES(ID),
    
    ID_USERS_FROM_POSTS NUMBER,
    CONSTRAINT USERS_FROM_POSTS_FK FOREIGN KEY(ID_USERS_FROM_POSTS) REFERENCES USERS(ID),
    
    ID_FORUM NUMBER,
    CONSTRAINT FORUM_FK FOREIGN KEY(ID_FORUM) REFERENCES FORUM_POSTS(ID),
    
    TITLE NVARCHAR2(50),
    CONTENTss CLOB,
    IS_POLL CHAR(1) DEFAULT 'N' CHECK(IS_POLL = 'N' OR IS_POLL ='Y'),
    DATEs TIMESTAMP,
    IP NVARCHAR2(20)
)
