CREATE TABLE FORUM_POLLS_OPTIONS(
    ID NUMBER,
    CONSTRAINT FORUM_POLLS_OPTIONS_ID PRIMARY KEY(ID),
    
    ID_FORUM_POSTS NUMBER,
    CONSTRAINT FORUM_POSTS_FK_FROM_POLLS FOREIGN KEY(ID_FORUM_POSTS) REFERENCES FORUM_POSTS(ID),
    
    TITLE NVARCHAR2(50),
    DATEs TIMESTAMP
)
