CREATE TABLE FORUM_POLLS_OPTIONS_VOTES(
    ID NUMBER,
    CONSTRAINT FORUM_POLLS_OPTIONS_VOTES_ID PRIMARY KEY(ID),
    
    ID_FORUM_POLLS_OPTIONS NUMBER,
    CONSTRAINT FORUM_POLLS_OPTIONS_FK FOREIGN KEY(ID_FORUM_POLLS_OPTIONS) REFERENCES FORUM_POLLS_OPTIONS(ID),
    
    ID_USERS_FROM_VOTES NUMBER,
    CONSTRAINT USERS_FROM_VOTES_FK FOREIGN KEY(ID_USERS_FROM_VOTES) REFERENCES USERS(ID),

    DATEs TIMESTAMP,
    IP NVARCHAR2(20)
)