CREATE TABLE SUPPLIERS(
    SUPPLIER_ID NUMBER,
    CONSTRAINT SUPPLIERS_PK PRIMARY KEY(SUPPLIER_ID),

    COMPANY_NAME NVARCHAR2(100) NOT NULL,
    CONTACT_NAME NVARCHAR2(100),
    CONTACT_TITLE NVARCHAR2(100),
    ADDRESS NVARCHAR2(100),
    CITY NVARCHAR2(100),
    REGION NVARCHAR2(100),
    POSTAL_CODE NUMBER(20),
    COUNTRY NVARCHAR2(100),
    PHONE NUMBER(20),
    FAX NUMBER(20),
    HOME_PAGE NVARCHAR2(100)
)