CREATE TABLE AUTHOR(
ID NUMBER,
    --PRIMARY KEY - (NOT NULL && UNIQUE)
CONSTRAINT AUTHOR_PK PRIMARY KEY(ID),
    --NOT NULL - значение не может буть пустое
NAME NVARCHAR2(50) NOT NULL,
    --UNIQUE - значение должно быть уникальное
LAST_NAME NVARCHAR2(50) UNIQUE,   
    --DEFAULT - значение по умолчанию если не указано значение
COUNTRY NVARCHAR2(50) DEFAULT 'ENGLAND',
AGE NUMBER DEFAULT 0,
    --CHECK() - значение с условием
ARTICAL_COUNT NUMBER CHECK(ARTICAL_COUNT > 10),
CONSTRAINT CHECK_COUNTRY CHECK(COUNTRY != 'CHINA' AND LAST_NAME!= 'TEST_LN')
)h