CREATE TABLE TORUM_POLLS_OPTIONS(
    ID NUMBER,
    CONSTRAINT TORUM_POLLS_OPTIONS_ID PRIMARY KEY(ID),
    
    ID_TORUM_POSTS NUMBER,
    CONSTRAINT TORUM_POSTS_FK_FROM_POLLS FOREIGN KEY(ID_TORUM_POSTS) REFERENCES TORUM_POSTS(ID),
    
    TITLE NVARCHAR2(50),
    DATEs TIMESTAMP
)
