CREATE TABLE TORUM_POSTS(
    ID NUMBER,
    CONSTRAINT TORUM_POSTS_PK PRIMARY KEY(ID),
    
    ID_TORUM_SUBCATEGORIES NUMBER,
    CONSTRAINT TORUM_SUBCATEGORIES_FK FOREIGN KEY(ID_TORUM_SUBCATEGORIES) REFERENCES TORUM_SUBCATEGORIES(ID),
    
    ID_USERS_FROM_POSTS NUMBER,
    CONSTRAINT USERS_FROM_POSTS_FK FOREIGN KEY(ID_USERS_FROM_POSTS) REFERENCES USERS(ID),
    
    ID_TORUM_POSTS NUMBER,
    CONSTRAINT TORUM_POSTS_FK FOREIGN KEY(ID_TORUM_POSTS) REFERENCES TORUM_POSTS(ID),
    
    TITLE NVARCHAR2(50),
    CONTENTss CLOB,
    IS_POLL CHAR(1) DEFAULT 'N' CHECK(IS_POLL = 'N' OR IS_POLL ='Y'),
    DATEs TIMESTAMP,
    IP NVARCHAR2(20)
)
