CREATE TABLE TORUM_SUBCATEGORIES(
    ID NUMBER,
    CONSTRAINT TORUM_SUBCATEGORIES_PK PRIMARY KEY(ID),
    
    ID_TORUM_CATEGORIES NUMBER,
    CONSTRAINT TORUM_CATEGORIES_FK FOREIGN KEY(ID_TORUM_CATEGORIES) REFERENCES TORUM_CATEGORIES(ID),
    
    TITLE NVARCHAR2(50),
    DESCRIPTIONs NVARCHAR2(1000),
    DATEs TIMESTAMP,
    IP NVARCHAR2(20)
)