CREATE TABLE TORUM_CATEGORIES(
    ID NUMBER,
    CONSTRAINT TORUM_CATEGORIES_PK PRIMARY KEY(ID),
    
    TITLE NVARCHAR2(50),
    DESCRIPTIONs NVARCHAR2(1000),
    DATEs TIMESTAMP,
    IP NVARCHAR2(20)
)