--ALTER TABLE NAME
--ADD NAME TYPE ..

--ALTER TABLE NAME
--DROP COLUMN NAME

--ALTER TABLE NAME
--MODIFY COLUMN NAME TYPE ..;

ALTER TABLE CUSTOMER
  ADD AGE NUMBER;

ALTER TABLE CUSTOMER
  DROP COLUMN AGE;

ALTER TABLE CUSTOMER
  MODIFY CUSTNAME NVARCHAR2(90);

ALTER TABLE CUSTOMER
  ADD AGE NUMBER DEFAULT 0 NOT NULL ;