--имена клиентов, их город, имена менеджерова по продажам, и их город, где сумма
--сделки была больше 10000
SELECT SALESMAN.NAME, SALESMAN.CITY, CUSTOMER.CUSTNAME, CUSTOMER.CITY FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
WHERE EXISTS(SELECT * FROM DEAL WHERE CUSTOMER_ID=CUSTOMER.CUSTOMER_ID AND AMOUNT>10000);

--имена клиентов которые делали сделки в 2017-2018 годах
SELECT CUSTNAME  FROM CUSTOMER
JOIN DEAL ON CUSTOMER.CUSTOMER_ID = DEAL.CUSTOMER_ID
      AND EXTRACT(YEAR FROM DATES) BETWEEN 2017 AND 2018
GROUP BY CUSTNAME;

-- имя лучшего менеджера по продажам по сумме сделок за август 2017 года,
-- выводить несколько имен, если таких менеджеров несколько
SELECT SALESMAN.NAME FROM SALESMAN,(
  SELECT SALESMAN.NAME, SUM(DEAL.AMOUNT) FROM SALESMAN
    JOIN DEAL ON EXISTS(SELECT * FROM CUSTOMER
    WHERE CUSTOMER.CUSTOMER_ID=DEAL.CUSTOMER_ID AND CUSTOMER.SALESMAN_ID=SALESMAN.SALESMAN_ID AND
          EXTRACT(YEAR FROM DATES)=2017 AND EXTRACT(MONTH FROM DATES)=8)
  GROUP BY SALESMAN.NAME
ORDER BY 2 DESC)
WHERE ROWNUM=1;